version: "3.7"
services:
  spring-app:
    build: .
    image: spring-app
    ports:
      - "4000:8080"
    networks:
      - shared-network
    depends_on:
      - redis-service
  redis-service:
    image: redis
    networks:
      - shared-network
networks:
  shared-network: {}